"""Generate include/secrets.h from the gateway's keys.json and known_fw.json.

    cd firmware
    python make_secrets.py

Run the gateway once first so keys.json exists. After flashing the HONEST build of a
node, copy the `fw` from its boot line into ../gateway/known_fw.json and run this
again so the malicious build knows which fingerprint to imitate while idle."""
from __future__ import annotations

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
GATEWAY = os.path.join(HERE, "..", "gateway")

with open(os.path.join(GATEWAY, "keys.json"), encoding="utf-8") as fh:
    keys = json.load(fh)
fw_path = os.path.join(GATEWAY, "known_fw.json")
known = json.load(open(fw_path, encoding="utf-8")) if os.path.exists(fw_path) else {}

lines = ["// generated by make_secrets.py — do not commit", "#pragma once", ""]
for node, macro in (("A", "NODE_A"), ("B", "NODE_B")):
    lines += [f"#if defined({macro})",
              f'#define NODE_KEY_HEX "{keys[node]}"',
              f'#define HONEST_FW_FINGERPRINT "{known.get(node, "0" * 64)}"',
              "#endif", ""]

out = os.path.join(HERE, "include", "secrets.h")
with open(out, "w", encoding="utf-8") as fh:
    fh.write("\n".join(lines))
print(f"wrote {out}")
